name:    derive-has-field
version: 0.0.1.6
github: "chiroptical/derive-has-field"
license: MIT
author: "Barry Moore II"
maintainer: "chiroptical@gmail.com"
copyright: "Barry Moore II"
synopsis: Derive HasField instances with Template Haskell
category: "Template Haskell"

description:
  A Template Haskell function to derive HasField instances to utilize
  OverloadedRecordDot more effectively.

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- template-haskell >= 2.5 && < 2.20
- th-abstraction > 0.4 && < 0.7

default-extensions:
- DeriveGeneric
- ImportQualifiedPost
- LambdaCase
- OverloadedStrings
- RecordWildCards
- TypeApplications

library:
  source-dirs: src

tests:
  derive-has-field-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - derive-has-field
    - hspec >= 2.10.10 && < 2.11
